blog/urls.py
from django.urls import path

from .views import PostListView, PostDetailView


app_name = "blog"

urlpatterns = [
    path("", PostListView.as_view(), name="home"),
    path("<slug:slug>/", PostDetailView.as_view(), name="post_detail"),
]

ostadsgo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("", include("blog.urls")),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from tinymce.models import HTMLField


STATUS = ((0, "Draft"), (1, "Publish"))


class Tag(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    updated_on = models.DateTimeField(auto_now=True)
    content = HTMLField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    tags = models.ManyToManyField(Tag, related_name="tags")

    class Meta:
        ordering = ["-created_on"]

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Post



class PostListView(ListView):
    model = Post
    template_name = "blog/home.html"
    context_object_name = "posts"


class PostDetailView(DetailView):
    model = Post
    template_name = "blog/post_detail.html"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" 
          integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" 
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <header>
      {% include "includes/navbar.html" %}
      <hr>
    </header>
    <main class="main">
      {% block content %}{% endblock content %}
    </main>
    <footer></footer>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/blog/home.html
{% extends 'base.html' %} 
{% load jalali_tags %}
{% block title %}وبلاگ سعید غلامی{% endblock title %}
{% block content %}
<section class="cards">
{% for post in posts %}
  {% if post.status %}
    <a href="{% url 'blog:post_detail' post.slug %}">
      <ul class="card">
        <div class="card-header">
          <li><h1>{{ post.title }}</h1></li>
          <div class="published-date">
            <li class="flex"><p>{{ post.author.username }}</p></li>
            <li class="flex"><p>{{ post.updated_on|to_jalali:"%Y/%m/%d" }}</p></li>
          </div>
          <li class="tags">
            {% for tag in post.tags.all %}
              <p class="tag">{{ tag.name }}</p>
            {% endfor %}
          </li> <!-- end of tags -->
        </div>
        <li><p>{{ post.content|safe }}</p></li>
      </ul>
    </a>
  {% endif %}
{% endfor %}
</section>
{% endblock content %}

templates/blog/index.html
{% extends 'base.html' %} 
{% block title %}وبلاگ سعید غلامی{% endblock title %}
{% block content %}
<section class="cards">
{% for post in posts %}
  {% if post.status %}
    <a href="#">
      <ul class="card">
        <li class="card-item"><h1>{{ post.title }}</h1></li>
        <li class="card-item"><p>{{ post.content }}</p></li>
      </ul>
    </a>
  {% endif %}
  {% endfor %}
</section>
{% endblock content %}

templates/blog/post_detail.html
{% extends 'base.html' %} 
{% block title %}وبلاگ سعید غلامی{% endblock title %}
{% block content %}
  <h1>{{ post.title}}</h1>
  <p>{{ post.content }}</p>
{% endblock %}

templates/includes/navbar.html
{% load static %}
<nav class="navbar">
  <a href="{% url 'blog:home' %}" class="logo">سعید غلامی</a>
  <div class="social-links">
    <a class="social-link" href="https://instagram.com/ostadsgo"><i class="fa-brands fa-instagram"></i></a>
    <a class="social-link" href="https://github.com/ostadsgo"><i class="fa-brands fa-github"></i></a>
    <a class="social-link" href="https://twitter.com/ostadsgo"><i class="fa-brands fa-twitter"></i></a>
  </div>
</nav>